# Generated by Django 4.1.7 on 2023-03-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('abilities', models.JSONField()),
                ('artist', models.CharField(default=None, max_length=512, null=True)),
                ('ancientTrait', models.JSONField()),
                ('attacks', models.JSONField()),
                ('convertedRetreatCost', models.SmallIntegerField()),
                ('evolvesFrom', models.CharField(default=None, max_length=512, null=True)),
                ('flavorText', models.TextField()),
                ('hp', models.SmallIntegerField()),
                ('images', models.JSONField()),
                ('legalities', models.JSONField()),
                ('regulationMark', models.CharField(default=None, max_length=5, null=True)),
                ('name', models.CharField(default=None, max_length=512, null=True)),
                ('nationalPokedexNumbers', models.JSONField()),
                ('number', models.CharField(default=None, max_length=16, null=True)),
                ('rarity', models.CharField(default=None, max_length=512, null=True)),
                ('resistances', models.JSONField()),
                ('retreatCost', models.JSONField()),
                ('rules', models.JSONField()),
                ('sets', models.JSONField()),
                ('subtypes', models.JSONField()),
                ('supertype', models.JSONField()),
                ('tcgplayer', models.JSONField()),
                ('types', models.JSONField()),
                ('weaknesses', models.JSONField()),
            ],
        ),
    ]
