# Generated by Django 4.1.7 on 2023-03-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cards',
        ),
    ]
