# Generated by Django 4.1.7 on 2023-03-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_card_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='ancientTrait',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='attacks',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='convertedRetreatCost',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='flavorText',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='hp',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='images',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='legalities',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='nationalPokedexNumbers',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='resistances',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='retreatCost',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='rules',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='sets',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='subtypes',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='supertype',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='tcgplayer',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='types',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='weaknesses',
            field=models.JSONField(default=None, null=True),
        ),
    ]
