# Generated by Django 4.1.7 on 2023-03-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_cards_ancienttrait_alter_cards_attacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
