# Generated by Django 4.1.7 on 2023-03-15 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_cards_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
