# Generated by Django 4.1.7 on 2023-03-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0004_alter_card_set_options'),
        ('cards', '0006_card_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sets',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sets.card_set'),
            preserve_default=False,
        ),
    ]
