# Generated by Django 4.1.7 on 2023-04-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.SmallIntegerField(default=None, max_length=16, null=True),
        ),
    ]
