# Generated by Django 4.1.7 on 2023-03-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_set',
            options={'ordering': ('-releaseDate',)},
        ),
    ]
