# Generated by Django 4.1.7 on 2023-03-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_alter_card_set_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_set',
            options={'ordering': ('releaseDate',)},
        ),
    ]
