# Generated by Django 4.1.7 on 2023-03-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0003_alter_card_set_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_set',
            options={},
        ),
    ]
